### ISSUE TITLE
Button for Zip Files should say "Download Content"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#1002]
This will have to be implemented in Figgy by adjusting the DAO creation process to set a label that says "Download Content" instead of "View Digital Content"

In ASpace the DAO on synchronization for a zip should say "Download Content" as the label.

**Comment by tpendragon** [comment]
https://findingaids.princeton.edu/catalog/C1436_c547

**Comment by hackartisan** [comment]
There will also need to be a migration for all the zip files currently in figgy. As part of closing this ticket, if the migraiton is quick to write then we should write it. Otherwise, if it's possible to provide some analysis of which or how many objects we're talking about that may be helpful to ADAPT.
