### ISSUE TITLE
Generate wireframes for improving discoverability of online content

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#1099]
Per 2022 user testing, users find it confusing that icons/badges for digital content appear at both the component-level where there is digital content as well as parent levels, which in many cases are not fully digitized, i.e. badges display at a series level even though not all of the materials within the series have been digitized. Users found it confusing trying to understand what was available digitally. Thus, similar to how access restriction badges are applied, those for digital content should only appear at the level at which there is digital content, not at parent levels as well with the exception of the collection level, which should still note that a collection "Has Online Content."

**Comment by sdellis** [comment]
[Relevant Highlight Reel](https://drive.google.com/file/d/19oZF-wcokWRNVmyHLpLwQuXS2c_cCxTk/view?usp=sharing)

**Comment by sdellis** [comment]
A few ideas from DLS review on 9/9/2022:

1. Add "Has online content" icons to the series view (in main content pane)
2. Change icon for branch-level nodes that may have online components? We have info from solr about which components have online content. Can we add this to the search results? How can we emphasize 
3. Create a link (perhaps from "has online content" tag at the top) to only online results in collection (like Duke). Issue is that you lose hierarchy.
4. ... or create a toggle to filter out all non-online content from the collection page view (not search results)
5. Update the tooltip to have clearer info "has online content" instead of "online"
6. Create better visibility in the banner for filtering online content. (see Duke) 
7. Try to come up with a way to draw attention to online content without depending solely on icons.

Success criteria for this ticket is a set of wireframes for review with PO's.

**Comment by tpendragon** [comment]
There was some more discussion about this here: https://github.com/pulibrary/pulfalight/issues/694, which we're closing.

**Comment by sdellis** [comment]
Here is a fairly complete [set of wireframes](https://xd.adobe.com/view/1a8defd5-0cd8-4715-a5c1-9cb7795d2ece-4fde/) based on everyone's feedback. I added icons to parents of online content that are grey in color to distinguish. Only the green icons actually have online content. Questions/comments can be input directly to the prototype, or dropped here.

**Comment by faithc** [comment]
Thanks for your work on these, Shaun. They're looking promising. :) Should the group schedule a separate meeting to review these together before the end of the sprint?

**Comment by ccleeton** [comment]
I think a meeting to discuss would be great. There are definitely some things in there that I really like!!!

**Comment by sdellis** [comment]
Here are the final, approved wireframes to close this ticket: https://xd.adobe.com/view/1a8defd5-0cd8-4715-a5c1-9cb7795d2ece-4fde/
