### ISSUE TITLE
Seamless interaction with Aeon

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#117]
Seamless login to Aeon (currently have to login once items are requested, can be disorientating to leave one environment and go to another; hard to know where to return, Aeon doesn't recognize that you've already logged in prior to requesting materials and forces you to login again)

**Comment by tpendragon** [comment]
We're moving this to the backlog for now, we've found we're unable to implement this at the moment. For now users will have to redirect to the Aeon page as they currently do.

**Comment by sdellis** [comment]
The Aeon API updates that would likely allow us to submit requests via POST with an auth token was scheduled for Q3 earlier this year. Now their site says Q4. I say "likely" because there seems to be no itemized list of what new API actions they are adding. This was a "wishlist" feature if things fell into place in time, but it's not doable at the moment.

**Comment by sdellis** [comment]
FYI @tpendragon  - I checked in on this with Atlas Systems and this was the response: 

> Hi Shaun,
> In the next version of Aeon (planned for release by the end of the year), we are adding a request creation endpoint to the Aeon API. So this functionality should be available soon and we will have more information as the work nears completion. Please let me know if you have any specific needs for request creation or any questions.
> 
> Best,
> Katie Gillespie

**Comment by tpendragon** [comment]
This is impossible until Aeon's updated. Closing for now.
