### ISSUE TITLE
Implement collection-level notes, including filtering down to child components

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#119]
Documentation: https://docs.google.com/spreadsheets/d/1fKd5t9Xk_Ph1MD5zt2O2LwSWfLeNQjBYtDM6fk8qH9k/edit#gid=0

To close this ticket ensure all the fields listed in the above spreadsheet "For developers" sheet show up in the tabs listed in the "desired behavior" column from the spreadsheet.

**Comment by hackmastera** [comment]
An example record would be really helpful here. Which notes?

**Comment by faithc** [comment]
It's somewhat difficult to determine which notes are currently filtering down due to how data is organized/broken up. We just want to make sure that the same logic or criteria that's being implemented on the current site that allows notes at the parent level that are not supplanted by notes in child components to filter down is mirrored here. I think it would make sense to review the criteria for the current site and compare it to the criteria in pulfalight to determine which notes are replicated? Assuming this is something @regineheberlein and @sdellis could assist with? 

Though we may want to review which notes filter down with our colleagues on ADAPT and public services. On pulfalight, it appears that the acqinfo element is filtering down to child components (https://pulfalight-staging.princeton.edu/catalog/AC351AC351_c01); this note doesn't display on child components on the current site; but perhaps we want it to?"

**Comment by faithc** [comment]
Though, we do know that we do NOT want the RULES OR CONVENTIONS note, that currently shows in the Overview section, to display. :)

**Comment by tpendragon** [comment]
@faithc We're having a hard time figuring out how to work this ticket. Can you find an example in the staging site where it's showing notes it shouldn't, or not showing a note it should so we can make this actionable? Even a new issue per note would be super helpful.

**Comment by tpendragon** [comment]
Maybe https://github.com/pulibrary/pulfalight/issues/286 is the documentation for this and we just need to do that work first?

**Comment by faithc** [comment]
Yes. The data in the spreadsheet explains how collection-level notes should be managed. Thanks.

**Comment by faithc** [comment]
Actually, @regineheberlein, does the encoding that we included in the spreadsheet still apply now that we're talking about ASpace records?

**Comment by regineheberlein** [comment]
@faithc No, that needs to be revised--it'll be wrong especially for the descgrp cases.

**Comment by faithc** [comment]
Drats. How might you propose doing that? I'm not familiar with the ASpace exports at all. Should this be brought to Will and Armando's attention?

**Comment by regineheberlein** [comment]
@tpendragon Do you need the EAD nesting structures of those notes to be revised for ASpace EAD flavor? Do you even use the EAD exporter anymore? ASpace keeps notes associated with resource/archival object records in "notes"=>[].

**Comment by tpendragon** [comment]
@regineheberlein It'd be helpful if they could be revised. We could probably stumble our way through it if y'all don't have time, but I can't promise much accuracy. We still use the aspace EADs.

**Comment by regineheberlein** [comment]
Will do! @tpendragon still the SVN ones? Or can you point me to where test EAD files now live?

**Comment by regineheberlein** [comment]
@tpendragon Done, based on the SVN ones for now. @faithc NB that some of the instructions in the Notes column are also now obsolete; I've added this where I noticed

**Comment by faithc** [comment]
Thanks, @regineheberlein!
