### ISSUE TITLE
Solr is timing out when running AspaceIndexJobs

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#1262]
[PULFALight/production] RSolr::Error::Timeout: RSolr::Error::TimeoutURI: http://lib-solr8-prod.princeton.edu:8983/solr/pulfalight-production/update?wt=jsonRequest Headers: {"Content-Type"=>"application/json"}Request Data: "[{\"id\":\"C0171\",\"ead_ssi\":\"C0171\",\"title_ssm\":\"M. L. Parrish Collection of Victorian Novelists\",\"title_teim\":\"M. L. Parrish Collection of Victorian Novelists\",\"subtitle_ssm\":\"M. L. Parrish Collection of Victorian Novelists\",\"subtitle_teim\":\"M. L. Parrish Collec...

## Backtrace

    line 60 of [PROJECT_ROOT]/app/jobs/aspace_index_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/90459110)

**Comment by tpendragon** [comment]
Things we learned:

* The heap on lib-solr-prod4 was still high because it hadn't been restarted since the changes to its configuration. Restarting it brought down the heap.
* Faraday was timing out waiting for the solr update. We can increase the timeout in `blacklight.yml` to let it wait longer. 15 minutes let some index.
* The pulfalight-worker1 box was out of space because it dumped the EAD to the log every time it failed, and it failed every time.
* We learned that the solr boxes have no firewalls restricting their communication.
