### ISSUE TITLE
Remove container information from unittitles

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#132]

**Comment by sdellis** [comment]
@apferrar What does this issue mean? What is the context?

**Comment by faithc** [comment]
@sdellis Hi Shaun- this relates to something the previous WG had discussed. This may be more of a design-related issue than one related to functionality(?); but as with the current site, we would like to privilege description over container information. So, rather than having description display as such: "Folder 2: Letter from Abraham Lincoln to James Gordon Bennett, 1865," where the container information is displayed first, we'd like the order to be reversed. (This is the collection I'm using as an example: https://pulfalight-staging.princeton.edu/catalog/C0094.) This method also makes sense since, as you know, the description of an intellectual grouping can be associated with several containers.

**Comment by jrgriffiniii** [comment]
This is addressed within the Traject Solr indexing configuration.

**Comment by tpendragon** [comment]
We don't add container information anymore.
