### ISSUE TITLE
add restriction note to request cart

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#1328]
The request cart should include a note when materials someone is attempting to request are restricted.

**Comment by ccleeton** [comment]
@ccleeton will provide the text we want it to have.

**Comment by sdellis** [comment]
A couple of implementation notes... 

In the screenshot below, the first item in the Request Cart is restricted from access. Instead of displaying "View this item at the Mudd Manuscript Library" it should indicate that the user will not be able to access the content they are trying to request. 

There are a number of edge cases in which an item marked as "restricted" may be available to the user (i.e. the embargo date has passed, it was mislabeled, the user has special privileges, etc.) I think something to the effect of "There is restricted access to this item. If you believe this restriction is in error or there are special circumstances, you may leave a note to the Special Collections Staff and continue with the request." @ccleeton will provide the final text. 

![request-cart-restricted](https://github.com/user-attachments/assets/6eb37f04-ad40-4b16-a638-a2a6f0b10ed1)

**Comment by ccleeton** [comment]
Sara and I discussed that the terminology needs to be brief so please move ahead with the following. 

"Item may need to be reviewed by staff for access"
