### ISSUE TITLE
Display folder number ranges at the parent level in addition to the extent note that says however many folders or containers are represented by the parent level

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#133]

**Comment by sdellis** [comment]
@apferrar Is there a screen shot for this, or example we can see from the current site? This applies to any containers, not just folders, correct?

**Comment by faithc** [comment]
@sdellis Yes, Shaun; this would apply to any container. One example is here: https://pulfalight-staging.princeton.edu/catalog/C1352. Navigate to the component for "Reeve, Tapping, 1770-1810." The request is for all of the associated folders (the folder range) to display (after the unittitle) as well as the extent info, which in this case would be 5 folders.

**Comment by jrgriffiniii** [comment]
I'm not certain that this is required any longer given the mockups present in https://xd.adobe.com/view/b8b645f7-4321-42d0-50a7-bcfbe9fdcb1d-ce87/screen/edcb6cef-4365-4fc4-8364-537dd96d849b/Series-Contents-and-Arrangement

**Comment by faithc** [comment]
I think this request still stands as it's asking for container information (box number(s) and/or folder number(s)) to display in addition to extent information (number of box(es) and/or folder(s)). Both pieces of info display on the current site in records for terminal components; though not in the tree/ToC view. For example, see https://findingaids.princeton.edu/collections/C1599/c2. 
I'd be ok with mirroring this functionality/design in pulfalight rather than having container info display at parent levels. What do you think, @apferrar?

**Comment by apferrar** [comment]
Agreed, the container information need not be in the tree/toc view, but in the actual record components (i.e. https://findingaids.princeton.edu/collections/C1599/c2 ) and in the list view (i.e. https://findingaids.princeton.edu/collections/C1599/c1 ). The original request and the request we're making now may not fully align.

**Comment by jrgriffiniii** [comment]
The `extent` element can be calculated, explaining how much material is actually featured within a component. The container might state "box 12-17, 21", or there might be XML links to the dsc[2] elements, and these must be resolved in order to generate the extent statement.

Currently, this is a part of the normalization routine, so if this is retained, then PULFALight should *not* need to compute anything. This is just a smaller problem with the Traject configuration.

**Comment by tpendragon** [comment]
@faithc @apferrar Can you look at what exists in the staging site and point us to what's wrong? We're a little confused.

**Comment by faithc** [comment]
I think this issue is resolved now? @apferrar?

**Comment by faithc** [comment]
Though I did spot another issue looking into this. The @physloc text notes associated with container records, which note where in the stacks an item is located, should not display on the site. This is for staff use only. For example, see: https://pulfalight-staging.princeton.edu/catalog/aspace_C1491_c5621. Should another issue be created for this?

**Comment by hackmastera** [comment]
@faithc I made https://github.com/pulibrary/pulfalight/issues/451

**Comment by faithc** [comment]
Thanks!

**Comment by tpendragon** [comment]
Closing this as it's resolved. We can reopen if we find a specific example.
