### ISSUE TITLE
Homepage Redesign

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#173]
Keyword search (basic search bar) should be most prominent feature on home/landing page similar to current site

Focus/cursor should be on the search field when page loads.

**Comment by jrgriffiniii** [comment]
I'm not certain that this requires wireframing, but I will ask and confirm.

**Comment by khanhvu98kk** [comment]
![Web 1920 – 3](https://user-images.githubusercontent.com/37961724/78827530-19057780-7998-11ea-9f9b-33de27ced047.png)

@apferrar @faithc Can we discuss this homepage wireframe in person with @sdellis this Friday at 12:30pm?

**Comment by faithc** [comment]
That works for me. Thanks

**Comment by apferrar** [comment]
Sounds great to me! Looking forward to it @khanhvu98kk

**Comment by sdellis** [comment]
**Notes from our 4/10 discussion:**

Feature Digital Content should be prioritized over Featured Blog Posts (should be changed from Recent Updates).

Locations and Hours should be limited to just Mudd and Firestone reading rooms.

"Search the Finding Aids" rather than just "Finding Aids"

Digitized Content could be curated or automated. Automated would be easiest, could be most recent, or randomly generated from what we have. How would thumbnails be automated? Curation would require more work on the part of SC staff, but could result in more compelling content that the dept wants to showcase. Need to have this conversation with AnnaLee, Squirrel, and others who may be responsible for this work.

Advanced Search feature?
Will basic search support boolean searching of multiple topics and phrases? Does the current approach of facet refinement support these boolean style features? This is a good topic for User Research. We should come up with "advanced search tasks" and see if facet refinement is enough for people or if they struggle. 

No one uses Locations. We want to retain Topics and Names as a feature, although they are outdated and ADAPT needs to revisit and revise. Are people actually using these features or not? Action item: Shaun will get some numbers on these. Need a way to "Browse Collections" that does not involve a blank search.

**Comment by apferrar** [comment]
Happened upon potential blogs to pull content from and these are the top contenders: [PUL Manuscripts News](https://blogs.princeton.edu/manuscripts/), [Mudd Manuscript Library Blog](https://blogs.princeton.edu/mudd/), [Notabilia](https://blogs.princeton.edu/notabilia/) (though related to rare books, so perhaps not), [RBSC News & Events](https://blogs.princeton.edu/rbsc/) (though hasn't been updated in quite a while and is a little boring, so maybe not).

**Comment by faithc** [comment]
Thanks, @apferrar. Another top contender would definitely be the Firestone Tech Svs blog, "This Side of Metadata" that the MSS processors primarily contribute to: https://blogs.princeton.edu/techsvs/. I would say the top three are PUL MSS News, Mudd, and This Side of Metadata.

**Comment by jrgriffiniii** [comment]
There should be an Epic created for the implementation of the design.

**Comment by jrgriffiniii** [comment]
Certain portions of the redesign are *not* going to be scoped as MVP for this. They still need to be identified.

**Comment by jrgriffiniii** [comment]
"Recent Updates" and "Digital Content" would need to be automated, but may not be considered MVP. However, "Location and Hours" and "Request Materials" really should be MVP.

What does automation mean for each of these content blocks? Is there a pool of content for "Digital Content" which is sampled for the most recently digitized content? If there are descriptions, where are these pulled from?

**Comment by jrgriffiniii** [comment]
There were <dao> thumbnails which were used on PULFA 2.0, where thumbnail images were featured for collections if they were present.

Using this approach could provide a mechanism for determining how to readily showcase digital content with the thumbnails present.

**Comment by jrgriffiniii** [comment]
PULFALight should be notified of newly-added digital content for Figgy, with the carousel interface for the "Digital Content" updated with the new thumbnail. Figgy thumbnails can be associated with digitized content - what needs to be investigated is how this would be supported with the underlying data models for Figgy.

**Comment by jrgriffiniii** [comment]
The "Locations and Hours" data is already available, and the "Request Materials" can be approached for the MVP. The main search bar must remain prioritized for the MVP.

However, what are the boundaries for these two content blocks? Are we strictly reproducing existing functionality for the existing PULFA 2.0 site?

There may need to be a further conversation regarding these requirements, and incrementally enhancing the "Recent Updates" and "Digital Content" blocks should be considered.

**Comment by jrgriffiniii** [comment]
It should also be noted that archival collections has a script which aggregates the links for Figgy content, and insert these as <dao> elements into existing Finding Aid EADs. Hence, some of the automation has already been supported.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pulfalight/issues/238#issuecomment-651274837

**Comment by jrgriffiniii** [comment]
Please see https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/ for the approved design updates.

**Comment by jrgriffiniii** [comment]
Given that this seems close to completion, I'm going to proceed by placing this in the "Review/QA" Pipeline (please see https://github.com/pulibrary/pulfalight/issues/238#issuecomment-666566594)
