### ISSUE TITLE
Migrate pul_solr specs to this repository

### ISSUE THREAD

**Issue by khanhvu98kk** [pulibrary/pulfalight#196]
Specs to migrate: https://github.com/pulibrary/pul_solr/blob/master/spec/pulfalight/identifier_spec.rb

Delete the specs from pul_solr.

**Comment by hackmastera** [comment]
Here's the solr call to get the fixtures `http://localhost:8983/solr/plantain-core-dev/select?id=MC001-02-03&qt=document`

**Comment by jrgriffiniii** [comment]
Given the age and that this would certainly precede the shift towards the importation of EADs from ArchivesSpace, I'm going to close this with the understanding that collaborators have since been implementing test suites using Traject-transformed XML Documents (rather than stand-alone Solr Documents).

**Comment by jrgriffiniii** [comment]
I am sorry, I should have first opened a discussion before closing this without warning. This should be reopened given that there should be test Solr fixtures in place.

**Comment by hackartisan** [comment]
Most of the specs there would fail if migrated. I'm going to create issues instead.

**Comment by hackartisan** [comment]
Created:
- https://github.com/pulibrary/pulfalight/issues/525
- https://github.com/pulibrary/pulfalight/issues/526

Other tests are covered by:
- https://github.com/pulibrary/pulfalight/pull/419
- https://github.com/pulibrary/pulfalight/pull/460
