### ISSUE TITLE
Allow requesting of components with level="otherlevel" otherlevel="text"

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#213]
Creating this ticket per an issue in discussion on the pulfa repo: https://github.com/PrincetonUniversityLibrary/pulfa/issues/374. 

On the current site, components with child components encoded with level=”otherlevel” otherlevel=”text” are not requestable. Also, these child components don't display. For example, see [C0744.04 ](https://findingaids.princeton.edu/collections/C0744.04)(Garrett Collection of Ethiopic Scrolls). 

Question as to whether components with level=”otherlevel” otherlevel=”text” should look up to the first parent that does have container information. (Best practice has been to put container information on the lowest level to which it pertains.) This is @regineheberlein's suggestion.

@sdellis suggested adding these components as "struct map" metadata in Figgy as items will be easier to view if they're digitized; however seems as if this matter was already discussed per #211  

Again, please refer to https://github.com/PrincetonUniversityLibrary/pulfa/issues/374 for more detail.

**Comment by regineheberlein** [comment]
Best practice is to put container information on the terminal/leaf-level component. It is based on the assumption that that represents a retrievable physical item. However, we have exceptions where we have encoded components at the "sub-item" level (e.g. prayers in a prayer book, pages of a volume, photographs pasted into an album). These are identified with `c level='otherlevel' otherlevel='text'`.

I see two issues being brought up here:
1. Requesting currently looks for container information only on the terminal level. That means that requesting for these components is not enabled. (The logic being that you can't request a piece of an integral item, nor can you request something non-physical like text.) To address this, a condition is needed that, when an "otherlevel" component is encountered, looks up to the first ancestor that does have container information. (We may need to exclude dao-only (i.e. digital) components in this.)
1. In addition @sdellis is addressing the question of metadata in figgy, which pulls from the EAD component, i.e. does not show container information for "otherlevel" components. A similar condition may be needed here.

**Comment by tpendragon** [comment]
Can I propose we rename this ticket (in order to be actionable) to `Allow requesting of components with level="otherlevel" otherlevel="text"`?

**Comment by faithc** [comment]
I think renaming the ticket per your suggestion makes sense. 

The fact that these items aren't requestable on the current site was deemed to be a bug, so it would be great if we could address the requesting functionality at least as part of the mvp. As of now, the majority of items in the collection given as an example, C0744.04, are not requestable. This is why public services staff brought it to our attention.

**Comment by tpendragon** [comment]
Cool, thanks! 😄

**Comment by sdellis** [comment]
> However, we have exceptions where we have encoded components at the "sub-item" level (e.g. prayers in a prayer book, pages of a volume, photographs pasted into an album). These are identified with c level='otherlevel' otherlevel='text'.

@regineheberlein  I believe this bug can be fixed by putting the container information on the terminal nodes, treating them the same way we treat a single box that houses many components. Then people can request a page in a volume the same way they request a folder in a box. Would this be an acceptable solution?

**Comment by regineheberlein** [comment]
I believe @faith may have used the word "bug" (`The fact that these items aren't requestable on the current site was deemed to be a bug`) generically to describe that a problem exists, not to identify the bug itself.

In my opinion, changing the data to accommodate existing code is not a good solution. The policy has been that only retrievable physical items can be requestable. @sdellis I worry that what you're suggesting would make non-physical items requestable in the finding aid. That would create a different problem for Public Services, since they're not in fact retrievable, so we'd have to address that issue in the request bundling anyway (we'd have to treat them like folders in a box or something like that). 

If we're going to have to add a scenario anyway, I think it'd be much better to leave the container information on the physical item and add the scenario of non-retrievable othertypes to the code, not change the data to shoehorn it into existing code.

**Comment by jrgriffiniii** [comment]
This was summarized as permitting the requesting of non-physical resources (e. g. pages in a book, or photos in an album) - these are simply not possible to request by patrons apart from their larger whole unit (e. g. component of some kind).

**Comment by tpendragon** [comment]
This might be fixed. I'm looking at https://findingaids-beta.princeton.edu/catalog/aspace_C0744-04_c0614, can you confirm this is the case @faithc?
