### ISSUE TITLE
Draft interactive wireframes for each screen featured on PULFALight

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#238]
Please see https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/ for the final version of the approved wireframes.

**Comment by jrgriffiniii** [comment]
I'm not certain if this issue should detail the individual screens, or if this should be an Epic with child issues. I defer to @sdellis on this.

**Comment by jrgriffiniii** [comment]
This was created when the implementation team first discussed this as a possibility, but I now I suspect that this encompasses the refined, dynamic wireframes which are being produced for stakeholder review. I could certainly update the title of this should it no longer accurately represent the work which is being undertaken for this week.

**Comment by sdellis** [comment]
@faithc and @apferrar 
Here are a couple wireframes, one is the Collection Summary/Overview (aka, "front page" of a collection) and the other is a Component Detail. I am working on the Series View (the sortable table) now, but I'd like to get your feedback sooner than later.

**Collection Summary**
Here's what's different and why:
1. The DACS-level sections are no longer bundled into the tree navigation. Instead they form a sub-nav at the collection level. Whenever the user is looking at any series or components, the "Contents" tab is active. If the user clicks the Contents tab, they will get a Series view at the top level (wireframe is forthcoming).
2. I moved the "action items" to the bottom of the screen. These will not scroll, but will be like a persistent footer for the components. This is because it's a common pattern on mobile apps/devices to have action items near the bottom to make it easier on the thumbs. :)

Here are my outstanding questions:
1. "List View" is what I'm calling SPV. You can access it from the top of the tree, from any page in the collection. Is this an appropriate name and location?2. Topics, Names, and Collections. Do we really want to keep them in the main header? That is where the most important site-wide info goes and given that we know we have work to do on Topics and Names, should they still be so prominent?
3. What do you think about the Contents tab and showing the top level "Series View"?
<img width="1011" alt="CollectionSummary" src="https://user-images.githubusercontent.com/609368/80025294-644a7a80-84ae-11ea-98b5-530a5bca4788.png">

**Component Detail**
Here's what's different and why:
1. I moved the "action items" to the bottom of the screen. These will not scroll, but will be like a persistent footer for the components.
2. The tree view is based on the Mmenu layout and colors. We can tweak the colors (or remove them), but there are two things I want to point out. First, the "active" node on the tree will be the same background as the content and will tie in from the left. Second, if this node has children, the arrow will be on the right but will also be the active color. 

Here are my outstanding questions:
General thoughts?

<img width="1013" alt="ComponentDetail" src="https://user-images.githubusercontent.com/609368/80025307-69a7c500-84ae-11ea-99c5-e3340719a81c.png">

**Comment by faithc** [comment]
Thanks, @sdellis. I'll leave some comments here if that's ok even though we'll be speaking in person as well.
**Collection Summary**
Here's what's different and why:

The DACS-level sections are no longer bundled into the tree navigation. Instead they form a sub-nav at the collection level. Whenever the user is looking at any series or components, the "Contents" tab is active. If the user clicks the Contents tab, they will get a Series view at the top level (wireframe is forthcoming). **-I like this.**

I moved the "action items" to the bottom of the screen. These will not scroll, but will be like a persistent footer for the components. This is because it's a common pattern on mobile apps/devices to have action items near the bottom to make it easier on the thumbs. :) **-I'm ok with this placement; though I'm not sure we should be privileging features for mobile devices generally speaking?**

Here are my outstanding questions:

"List View" is what I'm calling SPV. You can access it from the top of the tree, from any page in the collection. Is this an appropriate name and location? **I think that's an appropriate location, especially since the goal is to eventually do away with this when functionality exists that makes this version obsolete. I don't think the terminology is intuitive. My suggestion would the "HTML view." We don't want to confuse users into thinking that this other view will provide more or different information than they can find in the "tree view," which is the issue on the current site.**

Topics, Names, and Collections. Do we really want to keep them in the main header? That is where the most important site-wide info goes and given that we know we have work to do on Topics and Names, should they still be so prominent? **I'm not seeing these in this particular wireframe, but I remember being ok with them being in main header since they didn't seem particularly visible due to the font size.**

What do you think about the Contents tab and showing the top level "Series View"? **I don't know if it's just the color schema, but it seems perhaps a bit too prominent on the page. I'm also not a fan of showing the top-level series view since the order of series doesn't typically have any significance. I think it should just display all of the parent components in a flat line, per the current site.**

**Component Detail**
Here's what's different and why:
I moved the "action items" to the bottom of the screen. These will not scroll, but will be like a persistent footer for the components. **I _think_ I'm ok with the request button being on the bottom as opposed to the top of the screen? (Also, will the label say "Request [xx] as it does on the current site?**

The tree view is based on the Mmenu layout and colors. We can tweak the colors (or remove them), but there are two things I want to point out. First, the "active" node on the tree will be the same background as the content and will tie in from the left. Second, if this node has children, the arrow will be on the right but will also be the active color. **Per my comment above regarding the Contents tab I feel like perhaps the colors or the boldness or some such is perhaps too prominent.** 

Here are my outstanding questions:
General thoughts? **I like it overall. Thanks.**

**Comment by sdellis** [comment]
Here's a series view that shows what it will look like when you scroll: https://xd.adobe.com/view/3660a78e-6fda-4eaf-7db5-09e9e7700340-4051/

**Comment by faithc** [comment]
Thanks, @sdellis. It's still unclear to me from these wireframes that one can scroll the entire ToC while reviewing a component record?

**Comment by sdellis** [comment]
**Feedback/Questions 4/23** from @faithc and @apferrar review of wireframes
_Single Page View / List View / Expanded View?_
We like the location, but may need to user test the label. We know we don't like "Entire Finding Aid".

_Do we need to provide downloadable PDFs?_
It would be much easier to allow people to print the SPV (with print CSS) vs. generating PDFs.

_The Table of Contents feels "heavy" in the wireframes. Can we make the proportions more similar to the current site?_
We have some constraints when it comes to developing for both mobile and accessibility. We need to make it easy for users to select either A) the component label or B) the expand/collapse icon. We also need to increase both  font and the spacing of the table. Here is the acceptance criteria we need to meet WCAG 2.1:

1. Target Size: [To be considered "Operable" the click target needs to be at least 44x44 pixels](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=144%2C1412#target-size). This is what [44x44 pixels](https://dummyimage.com/44x44/ffffff/000000.gif) looks like. This is a WCAG AAA requirement. We aim for AA compliance, so we don't legally have to comply, but it's what is recommended.
2. Legibility: WCAG has no Text Size requirement, but [requires that a user needs to be able to resize/scale text up to 200 times without losing any functionality or content to be "Perceptible"](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=144%2C1412#resize-text). This will be interesting to see how things wrap and how the hierarchy is represented at these sizes. The common browser default is a font size of 16px. We can go smaller than that, but I would definitely bump up our current TOC item size which is 11px. 

One thing I can do is look at playing with the color/grayscale values since the "heaviness" seems to come from the deeper nested items being darker and higher contrast. Something like this might be more fitting:
<img width="445" alt="Screen Shot 2020-04-23 at 1 06 16 PM" src="https://user-images.githubusercontent.com/609368/80128215-586cc000-8563-11ea-8e8f-5abbdeaed986.png">

**Comment by faithc** [comment]
i think it may be a combo of the color scheme and size.

**Comment by faithc** [comment]
crazy idea: what if the main page was a light grey and the ToC shades of white?

**Comment by sdellis** [comment]
**Feedback 4/23** from @apferrar and @faithc 

- Collections w/o Hierarchy
	- How do people sort these components without a "root node"? Contents and Arrangement in the current site allows one to sort on flat collections.
- Contents Tab
	- Does this go to SPV when clicked? 
- Question: Has Yale/Mark Custer implemented the ArchivesSpace SPV PUI plugin?
- Enable easy toggling between Expanded and Focused Views
- Fixed TOC menu that scrolls with you, but is scrollable itself (most promising approach)
- Explore moving the TOC Expand/Collapse icons to the left (more conventional)
- "Add to Cart" vs. "Request this {container}": decision is to keep "Request this {container}"

**Comment by sdellis** [comment]
@faithc and @apferrar it took me a while to find an example in the ArchivesSpace PUI, but [it looks like they finished the Expanded View](http://sandbox.archivesspace.org/public/repositories/3/resources/3/collection_organization) (aka, SPV). 

It looks similar to how I think we want ours to look, I intend to borrow from this in the Expanded View wireframe. I also like how the TOC follows you as you navigate. One thing to note: Unittitles are hidden from view and don't wrap, however one can drag the edge of the TOC to reveal longer names and to make it wider/narrower.

**Comment by sdellis** [comment]
Latest wireframes: https://xd.adobe.com/view/3660a78e-6fda-4eaf-7db5-09e9e7700340-4051/

**Comment by faithc** [comment]
Just some quick, initial thoughts. 

I actually find the ASpace PUI a bit clunky, fidgety (? I can't think of a good word, haha), and a little confusing in terms of having to use both scroll bars to navigate up and down the page and the ToC, particularly navigating to the top and "bottom" (since it continues to expand) of the page, and expanding the width of the ToC. There's a lot going on. 

Overall, the latest wireframes look great. Still think the ToC is a bit too large. I like the size of the ToC in the ASpace expanded view with the shortened titles. Perhaps some of the white space following the titles could be removed, though not sure whether the space is to accommodate the longest title/text string.

**Comment by sdellis** [comment]
@Faith Yes, I'm trying to accommodate the deepest hierarchy. This is how it looks at 8 deep, which we have several of (and it fails at this width):
<img width="261" alt="Screen Shot 2020-04-30 at 1 30 50 PM" src="https://user-images.githubusercontent.com/609368/80740965-df331700-8ae6-11ea-862d-7ebdcf29f9b5.png">

So, either we will need to widen it or have a way to manually expand the width of the TOC. Wrapping labels only works if you have the space to begin with.

Also, what do you think of using the PUI vocab and call it "Collection Organization" rather than "Content"?

**Comment by faithc** [comment]
ok, @sdellis; sounds good. thanks. 

And hmmm, think I prefer Contents (or Contents and Arrangement per pulfa 2.0). To me, collection organization, doesn't indicate the ability to discover/browse all of the materials in a collection. Might be a question to pose to our stakeholders.

**Comment by apferrar** [comment]
- @sdellis I like the wireframes, they make sense to me, though I will agree that the ToC seems a bit wide. 
- I agree with Faith that I'm not happy with how the ASpace page works, I kept thinking it wasn't loading correctly and the scrolling moves around too much in places I don't intend for it. I do like how you can drag the TOC to make it wider, though. 
- I like the phrase "collection organization" and think we should add it to whichever list we're keeping of potential naming options for user testing!
- I'd love to have a conversation about Greg Wiedeman's article in relation to what we're trying to accomplish with the new design. Maybe that can happen this afternoon.

**Comment by sdellis** [comment]
Agreed on the size of the ToC. Here's some revisions to the ToC: https://xd.adobe.com/view/3660a78e-6fda-4eaf-7db5-09e9e7700340-4051/

Click on the banner and you will see an "8 deep" mobile view.

**Comment by apferrar** [comment]
much better! thanks!

**Comment by sdellis** [comment]
@faithc and @apferrar I believe I've made all the changes we agreed to yesterday. We agreed that any screens that will not change will not need wireframes. Please review and let me know if I need to add any additional screens: 
https://xd.adobe.com/view/eb1c45d0-a56f-49a7-5b1d-13a2373ed9cc-9d2d/

**Comment by faithc** [comment]
Thanks, @sdellis. I had a chance to review and left some comments. I wonder if you, me, and @apferrar should actually chat about the collection-level notes. I left a comment about these on the 4th wireframe page.

**Comment by faithc** [comment]
re: PDFs, I just want to note here that UAlbany includes pdfs in ASpace and links to these from their instance of ArcLight. Perhaps we should do this as well.

**Comment by jrgriffiniii** [comment]
This is still pending final approval and review from the product owners.

**Comment by jrgriffiniii** [comment]
@sdellis sorry to trouble you, but might I please request the status of the wireframes?

**Comment by jrgriffiniii** [comment]
The link for the approved draft of the wireframes is https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/. I will update this in the body of this Issue.

**Comment by sdellis** [comment]
@jrgriffiniii the latest draft of the wireframes are here: https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/

There are a few details that we will be finalizing early next week, so these drafts are not approved yet. However, at this point it will be mainly vocabulary/language changes, so you can determine if we can proceed before sign-off.

**Comment by jrgriffiniii** [comment]
Thank you very much for this Shaun. Please freely object, but I'm going to proceed by placing this in the "Review/QA" Pipeline given that this seems close to completion.

**Comment by sdellis** [comment]
Final and approved wireframes are here: https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/grid

See comments for annotations.
