### ISSUE TITLE
Supporting Voyager records for ReCAP materials in <container> elements

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#539]
There currently exists a workflow in which colleagues manually encodes the location for ReCAP materials into the MARC records within the Voyager ILS in order to support Aeon-based requests for accessing the physical material.

ArchivesSpace Resource exports (as EAD XML) should consistently encode the location for these ReCAP materials (within the <container> element, I believe), and PULFALight must ensure that these can continue to be requested by users (as they currently can be using PULFA 2.0).

**Comment by jrgriffiniii** [comment]
Please be aware that this was discussed during a meeting of the ArchivesSpace Working Group Meeting (held on 12/01/20), and that there were concerns relating to how ArchivesSpace Resource location codes can be inserted into Voyager MARC records.

**Comment by jrgriffiniii** [comment]
@regineheberlein I apologize for being unavailable for the meeting earlier today. For my own clarification, did the questions regarding the ReCAP material in Voyager involve some feature support in ArchivesSpace? (i. e. are stakeholders requesting some pipeline between ArchivesSpace and Voyager to update the Voyager MARC records?)

**Comment by regineheberlein** [comment]
@jrgriffiniii 
As I understand it, this relates to the following situation:

Because of the ways our systems interoperate (or not), items stored at ReCAP must have a Voyager item record. These item records are currently added to Voyager by staff manually.

With the cutover to ASpace and pulfalight, there is a desire to automate this workflow and have ASpace top_containers with ReCAP locations exported from ASpace and imported to Voyager.

The ReCAP locations we use are 
rcpph
rcppf
rcppl
rcpxc
rcpxg
rcpxm
rcpxr

We also use the off-site location anxb; it may need to be included also.

**Comment by jrgriffiniii** [comment]
This lies within scope (and is superseded by https://github.com/pulibrary/pulfalight/issues/311)
