### ISSUE TITLE
Banner text for when full switch is made in March

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#667]
Welcome to the new Finding Aids site! We look forward to hearing your feedback! (POs Need to create and provide a link for feedback or survey)

The Seeley G. Mudd Manuscript Library is currently undergoing a renovation. In the coming months, as we prepare for the completion of this project, access to the collections will again become extremely limited. Please visit the [Access to Mudd Library During Renovation](https://library.princeton.edu/special-collections/policies/access-mudd-library-during-renovation) page on our website for the most up-to-date information, including dates when we will stop accepting digitization and reference requests that require access to the collections.

For more information about access during COVID-19, please visit our [Virtual Services ](https://library.princeton.edu/special-collections/services/virtual-services)page.

**Comment by sdellis** [comment]
@ccleeton we have been trying to reduce the amount of text in announcement banners, and how long banners stay up. I think some of this information would be better served at the points of context than in a "banner". Can we have a conversation about this soon?

**Comment by ccleeton** [comment]
My thoughts is that this particular banner won't need to be up for very long but @faithc and I are also open to other suggestions than a banner. Maybe a feedback bubble that is similar to the Ask Us bubble on the library main page.

**Comment by sdellis** [comment]
@ccleeton since I will be away next week, here is an attempt to tighten this up for the switch over. Let me know what you think. Totally open to rewording, would like to aim for this length. I'm trying to think of the most succinct way to get users the critical info. 

I left out the "feedback" link because we don't have one yet. I also think there are much better places for a feedback call to action. Let's address that when we are ready.

<img width="1232" alt="Screen Shot 2021-03-04 at 4 28 16 PM" src="https://user-images.githubusercontent.com/609368/110032955-c3039600-7d06-11eb-8be5-c6776cf500e0.png">

**Comment by ccleeton** [comment]
I have asked Sara for an edit to the Mudd one but I might not hear back until tomorrow on that one. We do need to link out from that to this - https://library.princeton.edu/special-collections/policies/access-mudd-library-during-renovation
That she will want for sure.

**Comment by ccleeton** [comment]
I am also asking if we can remove the covid one completely. I will let you know.

**Comment by ccleeton** [comment]
@sdellis This is the approved Mudd related banner text
The Seeley G. Mudd Manuscript Library is currently undergoing a renovation. As we prepare for the completion of this project, access to the collections will be extremely limited. Please visit the [Access to Mudd Library During Renovation](https://library.princeton.edu/special-collections/policies/access-mudd-library-during-renovation) page on our website for the most up-to-date information.

**Comment by sdellis** [comment]
@ccleeton no problem. I will update it, but there is one thing that is not clear to me in the approved text: 

It says access to _the collections_ will be extremely limited. Since Finding Aids has many collections outside, Mudd, does this refer to ALL collections in Finding Aids or only Mudd collections?

**Comment by ccleeton** [comment]
Only Mudd collections 

how about
access to these collections
