### ISSUE TITLE
Has Online Content Icon in collection - could this be clickable to show all online?

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#694]
Looking at this https://findingaids-beta.princeton.edu/catalog/MC076 at the collection level there is the "Has Online Content" Icon.

Could this be made to be clickable so that it shows all online?
@sdellis - @faithc mentioned that you all had discussed this a while back with Mandy but it wasn't recalled why this was a yes or no? Could you address?

**Comment by tpendragon** [comment]
Duke does this via a banner. See https://archives.lib.duke.edu/catalog/andrewsj

**Comment by ccleeton** [comment]
We had researchers do this in testing. I still find it frustrating that once I am in a collection I can't just narrow it down to the online

**Comment by sdellis** [comment]
The group decided that the best approach would be to have the toggle on the collection page to show full collection or just online content. It would be best to have an animated transition that removes/adds non-digitized components to the TOC, rather than going back to search results page. @faithc @ccleeton
