### ISSUE TITLE
 add the Ask Us button to the finding aids. 

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#779]
@faithc and I would like to discuss the options for adding a feedback "button" to pulfalight similar to the one on the PUL site. 
This would mostly benefit the staff at this moment. We are finding that staff are using Suggest a Correction, and direct messaging to POs instead of the slack channel. 

@sdellis I know that you mentioned we generally would wait on something like this for the public we are finding that there is a need now. If we added a feedback option, would it be something that goes into a ticketing system or a google form or something else? Could the form capture the URL of the page the user is on similarly to how the SAC works?

**Comment by sdellis** [comment]
@ccleeton and @faithc when you say "feedback button" are you referring to the "Ask Us" button in the lower right corner of the Library Website? We have a "feedback" link in the PULFA 2.0 site that has not seen activity in years, so I would want to make sure it gets use if we add it. 

I was under the impression that our strategy for inter-staff communication involved staff using Suggest a Correction, so I'm surprised that you are unhappy with its use. Have you asked staff to use the Slack channel instead? Were they resistant to that? Or are you saying that Slack is not sufficient either because it offers no way to track the feedback/suggestion?

Seems like we may want to schedule a meeting to discuss this in more detail?

**Comment by faithc** [comment]
Hi @sdellis- yes, @ccleeton and I were thinking that a "Site Feedback" button on every page of the site that links to a simple google form might be useful for a period of time at least for staff (and possible external users) to send questions or report issues and such about the site's functionality. The "Ask Us" button is really for reference questions and Suggest a Correction is only meant to communicate issues regarding description. We think it would be useful, based on recent communication we've received from staff, to have an option in addition to the pulfalight channel for staff to submit feedback related to site functionality as some staff seem hesitant to use slack and because of the convenience of referring to a specific page as an example. 

Would be happy to meet to discuss this. Thanks.

**Comment by sdellis** [comment]
We decided on 3/31/2021 that we would add the "Website Feedback" button/form to PulfaLight. @sdellis will make the case to begin work on an implementation. We also decided that in order for the feature to fulfill its potential, the Library should use it to actively solicit such feedback from staff, faculty, and researchers. 

Before using this in production, we will need to decide who the feedback goes to, whose responsibility it is to mediate and respond to the feedback, and how we decide to prioritize or take action on resolving any issues that are relayed by our users. These are higher level questions and @faithc and @ccleeton will organize future meetings to address them.

**Comment by ccleeton** [comment]
We are now experiencing issues with directing researchers to how they can contact us. We would like to add the Ask Us button to the finding aids. The libapp ask us should go to the Special Collections libanswers queue.

**Comment by ccleeton** [comment]
https://library.princeton.edu/special-collections/ask-us

**Comment by hackartisan** [comment]
Ask us button should look like the one on the library website: https://library.princeton.edu/

It should contain the fields in https://library.princeton.edu/special-collections/ask-us

It should be on the front page and direct to the special collections queue of libanswers.  Note that "Ask a question" on a component page also goes to this queue.

**Comment by sdellis** [comment]
I just want to check my assumptions about the Ask Us button: 

It should look identical to the Ask Us button on the Library Website, but the behavior should be different. In other words, we are NOT implementing Live Chat, but rather the click should display the modal pop-up we currently use for Ask A Question on collection pages (see screenshot). 

Is this correct, @Faith?

![Screen Shot 2022-04-26 at 12.47.51 PM.png](https://images.zenhubusercontent.com/5cba15f2e89c9c3b0c58e0d1/311e0093-e14e-4c57-bdc8-5de34a989407)

**Comment by sdellis** [comment]
There are two potential UX issues I see with this, although fairly minor. First, clicking on Ask Us should result in a title that is identical, whereas this one would be mismatched with the title being "Ask A Question". Second, people who are used to clicking on "Ask Us" for Live Chat in the Library site may be surprised that this feature is not consistent across our sites.

**Comment by faithc** [comment]
This is more a question for @ccleeton.

**Comment by ccleeton** [comment]
Could it say Ask Us A Question?
and I see the issue with the consistency however I do think most of our users use the FA and not the main library page as much so I think it will be ok.

**Comment by ccleeton** [comment]
We can't handle live chat. We really just want a way from the main landing page that people can contact us. There isn't something right now. However that needs to look.
