### ISSUE TITLE
Truncate Access Note before Request is sent to Aeon

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#781]
Access note is too long for call slips. Truncate to 75 characters before sending to Aeon.

![C1491 call slip 1](https://user-images.githubusercontent.com/609368/112681186-b88b7680-8e44-11eb-87cb-2b0f0a5a5ecc.jpg)

**Comment by sdellis** [comment]
@ccleeton I'm looking at the image you included (above). It looks like it already gets truncated after "Mater". Is this not the case?

**Comment by ccleeton** [comment]
It does seem to do that now yes. 
The whole note would be - "The collection is open for research. Toni Morrison's manuscript material, including drafts, typescripts, galleys, and proofs found in boxes 1-11; 13-19; 22-29; 32-47; 50-56; 59-62; and 64-66 are available only via digital access in the reading room. Material in boxes 280-291; 305-308; 310-318; 320; 323; and 325 will also be available only via digital access in the reading room pending digitization. A small amount of material is temporarily restricted at the request of the collection creator or due to the presence of personally identifiable or other legally protected information. For preservation reasons, physical access to original audio and visual media in a variety of magnetic and optic formats is restricted."
