### ISSUE TITLE
Viewer should not try to load downloadable audio files

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#946]
Some digital files (those in .zip format) should only be available via links to download. The viewer should not try to load zip files. 

Example collection of files that should not be loaded into the viewer:
https://findingaids.princeton.edu/catalog/AC465

**Comment by tpendragon** [comment]
I think these items just need their DAOs updated. I'm gonna update DAOs for this collection.

**Comment by tpendragon** [comment]
Updating the DAOs for this didn't work because of https://github.com/pulibrary/figgy/issues/4761

**Comment by tpendragon** [comment]
I'm not going to get this wrapped up today, but we should be able to put it off until next maintenance week (or further). I'm leaving high priority, but removing sudden priority label.

**Comment by hackartisan** [comment]
I don't see any viewers loading on those records. A clear example of what we're seeing that we don't expect to see would be helpful.

**Comment by hackartisan** [comment]
I found some that load viewers. Examples:
- https://findingaids.princeton.edu/catalog/AC465_c8
- https://findingaids.princeton.edu/catalog/AC465_c83

**Comment by kellybolding** [comment]
Hi all! I ran into the discussion about this ticket on the digital_library thread and I'm experiencing a similar issue as Valencia. I figured I would leave this here as another example in case it's helpful for solving this issue, but let me know if there's a more appropriate place to report this. Thanks!

I recently added zips to Figgy for the four components that are children of this one: https://findingaids.princeton.edu/catalog/C1372_c217

Three of them successfully have the "View Content" button that leads to a zip file download, as expected (ex. https://findingaids.princeton.edu/catalog/C1372_c269), but for some reason this one displays a non-functional viewer instead of the "View Content" button and zip download (https://findingaids.princeton.edu/catalog/C1372_c272).

**Comment by tpendragon** [comment]
For that last one I had to delete the digital object in ASpace and switch the object to flagged then back to complete for the right DAO to sync over. We'll fix this in a more general way as part of resolving this during a maintenance cycle. That last one should be fixed the next time pulfalight indexes.

**Comment by tpendragon** [comment]
I'm now updating DAOs for every component in Figgy.

**Comment by tpendragon** [comment]
All the DAOs have been updated - closing.
