### ISSUE TITLE
Rename Plantain to PULFAlight within the codebase and documentation

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#95]
This was renamed to PULFALight.

**Comment by hackmastera** [comment]
This issue is also relevant to the princeton_ansible repo.

**Comment by hackmastera** [comment]
Provisioned with ansible (follow-up PR to come) and deployed the app. I did some cleanup:

* Removed the old app config since we know having old app configs around can pollute env with bad values.
* turned off plantain workers service and deleted `/etc/systemd/system/plantain-workers.service`

Testing included:

* Checked `sudo passenger-status` to ensure the app was running from the new location
* Checked the UI to see that I can search, log in and create a bookmark
