### ISSUE TITLE
dash vs dot in older figgy records not showing online content 

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#954]
Many collections that previously had a . in the collection number and now have a - are not showing up as online in the finding aids.
Example:
https://findingaids.princeton.edu/catalog/AC107-06_c340
https://figgy.princeton.edu/catalog/055754ce-789d-4e71-aea5-e76dd4c042bb

Is there a way to fix this for the whole finding aids?

## Resolution

Find all source metadata identifiers which have a period in them in Figgy, convert them to dashes.

**Comment by phoebeno** [comment]
This also in ACLU: 
https://findingaids.princeton.edu/catalog/MC001-03-05_c07334
https://figgy.princeton.edu/catalog/c494d2c4-b223-4400-b7b3-d2280157bf88

**Comment by hackartisan** [comment]
Were all uses of `.` changed to `-`? Or is there a list? I'm not sure what the scale of this issue is.

@ccleeton I just changed the example you provided using the form in figgy, which causes the online content to come through. Could you take a look and see if it looks good still in figgy?

**Comment by tpendragon** [comment]
@ccleeton @phoebeno @faithc This got marked sudden priority. Presumably it's okay to push this to our next maintenance cycle - which would mean we'd look at bulk updating these the week of the 17th?

**Comment by phoebeno** [comment]
I think CC and FC are both out at the moment; the week of the 17th is not too far away for me. I would love to see the inheritance bug fixed first, as we have ACLU researchers coming in Jan. and the restrictions are not inheriting correctly to children

**Comment by faithc** [comment]
I'd defer to @ccleeton and @apferrar on this one, though addressing it the week of the 17th sounds doable to me. I thought that the PL maintenance cycle wasn't happening though until February or March? Is that no longer the case? 

@phoebeno - we're waiting for Regine to finish with the data cleanup before implementing this logic for accessrestrict notes since we identified data issues in MSS finding aids, correct? Unless it makes sense or is possible to apply it to repos aside from MSS or just ACLU for now?

**Comment by tpendragon** [comment]
@faithc The week of the 17th is a maintenance week, it's just easier to do these kind of between-cycle tickets during those times. The timing for the next work cycle for pulfalight hasn't changed.

**Comment by faithc** [comment]
Right, sorry. I confused myself with the lingo. Thanks for clarifying.

**Comment by ccleeton** [comment]
Sorry for the delay. Waiting for the maintenance week works for me.

**Comment by tpendragon** [comment]
All uses of `.` were changed to `-`

**Comment by tpendragon** [comment]
So the ID in Pulfalight was changed in the URL, but the actual call numbers still have periods in them. 

For example: https://aspace.princeton.edu/staff/resources/2161#tree::archival_object_733628 The call number for this is AC107.07_c897. If you put that in Figgy it works fine.

In fact, if you use the "-" version (which is only in the pulfalight URL) in Figgy then I think DAO updating wouldn't work, since it'd try to find the archival object and not find it (there's no "AC107-07_c897"). 

So I think there's a few things to do here:

1. Update all instances of "-" in Figgy with "." (this should only be new records I think?)
2. Update the Pulfalight javascript that looks up the viewer to use periods instead of dashes.
3. If a user enters a "-" and it finds a record whose actual call number is "." it should use that as the source metadata identifier.

**Comment by tpendragon** [comment]
On the bright side I think there's only 15 resources in Figgy that have the "dash instead of period":

```sql
figgy_production=# select id, metadata->'source_metadata_identifier'->>0 FROM orm_resources WHERE metadata @> '{"source_metadata_identifier": []}' AND metadata->'source_metadata_identifier'->>0 LIKE '%-%\_%' AND metadata->'source_metadata_identifier'->>0 NOT LIKE '%.%';
                  id                  |       ?column?
--------------------------------------+-----------------------
 db638171-5856-451d-a323-cf2a9414217b | AC105-03_c3166
 8017bdb4-a9e7-4cce-9474-39c90e1fbf96 | AC105-04_c149
 055754ce-789d-4e71-aea5-e76dd4c042bb | AC107-06_c340
 1cbeb7b2-c379-4657-9102-df8ec6943bfb | RCPXG-5830371-2_c0528
 b2f92225-3835-4445-94f2-d244400daf1c | AC104-03_c2
 d40d3ede-7eef-405e-955f-8103b6eff6fc | AC198-03_c1536
 06b00c73-a596-4ecf-93cb-da052c8fa875 | AC198-04_c3932
 06746e41-aa46-41e2-8994-8109051a9af2 | AC104-03_c6158
 88a81495-718d-41e9-9534-d19c5ddc4e91 | AC107-14_c1223
 ad0046c2-f183-41ff-8277-2e668df453ad | AC198-02_c610
 150e0667-9a69-46b8-8aea-66d3c61aa707 | AC107-10_c3187
 ec23d20b-a52d-4687-9ab6-f3f42d6b0f97 | AC105-02_c147
 c667b46f-c069-4f58-959a-99a2a967855f | AC198-03_c698
 86f45dd2-1e75-4a0d-a381-4a411ac39641 | AC105-04_c4644
 2fb9377d-f556-4d94-a2a7-e4d490eac9e1 | AC104-03_c1338
(15 rows)
```

**Comment by hackartisan** [comment]
> In fact, if you use the "-" version (which is only in the pulfalight URL) in Figgy then I think DAO updating wouldn't work, since it'd try to find the archival object and not find it (there's no "AC107-07_c897").

Figgy isn't searching by ID?

**Comment by hackartisan** [comment]
> Many collections that previously had a . in the collection number and now have a - 

So I read this ticket initially as saying that IDs had been changed in aspace. I think what @tpendragon is saying is that's not the case, that the only change was made in pulfalight for the purposes of having url-safe characters in the url. It sounds like we will keep the url that way but not use that form for anything else.

I think an ADR would be helpful here.

**Comment by tpendragon** [comment]
Records are fixed, ADR is in, and viewer queries appropriately.
